# Generated by Django 3.2.16 on 2023-11-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231125_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.post',),
        ),
    ]
