# Generated by Django 3.2.16 on 2023-11-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
